{
    "config": {
        "error": {
            "cannot_connect": "Falha na liga\u00e7\u00e3o",
            "invalid_auth": "Autentica\u00e7\u00e3o inv\u00e1lida",
            "unknown": "Erro inesperado"
        },
        "step": {
            "discovered_connection": {
                "data": {
                    "password": "Palavra-passe",
                    "username": "Nome de Utilizador"
                }
            },
            "manual_connection": {
                "data": {
                    "username": "Nome de Utilizador"
                }
            }
        }
    }
}